name: SDLC Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Linter (flake8)
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Run Security Scan (bandit)
        run: |
          pip install bandit
          bandit -r . --exclude venv

      - name: Run Tests (pytest)
        run: |
          pip install pytest
          PYTHONPATH=$PWD pytest --verbose --disable-warnings

      - name: Check Files Before Packaging
        run: ls -lah

      - name: Package Application
        run: |
          tar -czvf aes_project.tar.gz requirements.txt aes_encryption.py test_aes.py .github/README.md

      - name: Check Files After Packaging
        run: ls -lah
      
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: aes_encryption_package
          path: aes_project.tar.gz
