name: SDLC Pipeline with in-toto

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install in-toto
        run: |
          pip3 install in-toto
          echo "Verifying in-toto installation..."
          whereis in-toto-run
          

      - name: Retrieve in-toto Keys from Secrets
        run: |
          echo "${{ secrets.IN_TOTO_PRIVATE_KEY }}" > in-toto.key
          echo "${{ secrets.IN_TOTO_PUBLIC_KEY }}" > in-toto.pub
          chmod 600 in-toto.key  # Ensure key is secure

      - name: Run Linter (flake8)
        run: |
          pip install flake8
          in-toto-run --step linting --key in-toto.key --record-stream "flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics"

      - name: Run Security Scan (bandit)
        run: |
          pip install bandit
          in-toto-run --step security-scan --key in-toto.key --record-stream "bandit -r ."

      - name: Run Tests (pytest)
        run: |
          pip install pytest
          in-toto-run --step testing --key in-toto.key --products test_results.log --record-stream "pytest --verbose --disable-warnings"

      - name: Package Application
        run: |
          in-toto-run --step packaging --key in-toto.key --products aes_project.tar.gz --record-stream "tar -czvf aes_project.tar.gz requirements.txt aes_encryption.py test_aes.py README.md"

      - name: Generate SBOM
        run: |
          pip install cyclonedx-bom
          in-toto-run --step sbom-generation --key in-toto.key --products sbom.json --record-stream "cyclonedx-py requirements -o sbom.json"

      - name: Verify in-toto Layout
        run: |
          in-toto-verify --layout root.layout --layout-key in-toto.pub

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: aes_encryption_package
          path: aes_project.tar.gz

      - name: Upload SBOM Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom_file
          path: sbom.json
